"""Initial migration

Revision ID: a19c7d9056a6
Revises: 
Create Date: 2019-02-21 20:17:43.692359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a19c7d9056a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('name', table_name='role')
    op.drop_table('role')
    op.drop_table('association')
    op.drop_table('user')
    op.drop_table('movie')
    op.alter_column('snh', 'creater',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               nullable=True)
    op.alter_column('snh', 'post_lz',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_general_ci'),
               nullable=True)
    op.alter_column('snh', 'post_url',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               nullable=True)
    op.alter_column('snh', 'reply_num',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('snh', 'time',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('snh', 'time',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('snh', 'reply_num',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('snh', 'post_url',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               nullable=False)
    op.alter_column('snh', 'post_lz',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_general_ci'),
               nullable=False)
    op.alter_column('snh', 'creater',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_general_ci', length=255),
               nullable=False)
    op.create_table('movie',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=60), nullable=True),
    sa.Column('year', mysql.VARCHAR(length=4), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('body', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('association',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('movie_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], name='association_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='association_ibfk_1'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('role',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_index('name', 'role', ['name'], unique=True)
    # ### end Alembic commands ###
